### ISSUE TITLE
SyntaxError: unexpected MATH

### ISSUE THREAD

**Issue by 1davidmichael** [alleyinteractive/hubot-code-review#22]
I am currently having issues when trying to run this with a [standard Hubot install using the yeoman generator](https://github.com/hubotio/generator-hubot).

```
$ node --version
v8.11.3
$ npm --version
5.6.0
```

package.json
```
{
  "name": "mdp-hubot",
  "version": "0.0.0",
  "private": true,
  "author": "David Michael <david.michael@meredith.com>",
  "description": "Meredith Slack Hubot",
  "scripts": {
    "start": "bin/hubot --adapter slack"
  },
  "dependencies": {
    "hubot": "^2.19.0",
    "hubot-code-review": "*",
    "hubot-diagnostics": "0.0.2",
    "hubot-google-images": "^0.2.7",
    "hubot-google-translate": "^0.2.1",
    "hubot-help": "^0.2.2",
    "hubot-heroku-keepalive": "^1.0.3",
    "hubot-maps": "0.0.3",
    "hubot-pugme": "^0.1.1",
    "hubot-redis-brain": "0.0.4",
    "hubot-rules": "^0.1.2",
    "hubot-scripts": "^2.17.2",
    "hubot-shipit": "^0.2.1",
    "hubot-slack": "^4.5.3"
  },
  "engines": {
    "node": "8.11.x"
  }
}
```

external-scripts.json
```
[
  "hubot-diagnostics",
  "hubot-help",
  "hubot-heroku-keepalive",
  "hubot-google-images",
  "hubot-google-translate",
  "hubot-pugme",
  "hubot-maps",
  "hubot-redis-brain",
  "hubot-rules",
  "hubot-shipit",
  "hubot-code-review"
]
```

```
[Thu Jul 19 2018 08:39:39 GMT-0500 (CDT)] ERROR Unable to load /home/dmichael/Repo/review_hubot/node_modules/hubot-code-review/src/code-reviews: SyntaxError: unexpected MATH
  at Object.exports.throwSyntaxError (/home/dmichael/Repo/review_hubot/node_modules/coffee-script/lib/coffee-script/helpers.js:197:13)
  at Parser.parser.yy.parseError (/home/dmichael/Repo/review_hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:265:20)
  at Parser.parse (/home/dmichael/Repo/review_hubot/node_modules/coffee-script/lib/coffee-script/parser.js:537:22)
  at compile (/home/dmichael/Repo/review_hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:35:24)
  at Object.loadFile (/home/dmichael/Repo/review_hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:176:14)
  at Module.load (/home/dmichael/Repo/review_hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at tryModuleLoad (module.js:505:12)
  at Function.Module._load (module.js:497:3)
  at Module.require (module.js:596:17)
  at require (internal/module.js:11:18)
  at Object.<anonymous> (/home/dmichael/Repo/review_hubot/node_modules/hubot-code-review/src/code-reviews.coffee:10:15, <js>:4:17)
  at Object.<anonymous> (/home/dmichael/Repo/review_hubot/node_modules/hubot-code-review/src/code-reviews.coffee:10:1, <js>:344:4)
  at Module._compile (module.js:652:30)
  at Object.loadFile (/home/dmichael/Repo/review_hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:182:19)
  at Module.load (/home/dmichael/Repo/review_hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at tryModuleLoad (module.js:505:12)
  at Function.Module._load (module.js:497:3)
  at Module.require (module.js:596:17)
  at require (internal/module.js:11:18)
  at Robot.loadFile (/home/dmichael/Repo/review_hubot/node_modules/hubot/src/robot.coffee:355:9, <js>:224:20)
  at module.exports (/home/dmichael/Repo/review_hubot/node_modules/hubot-code-review/index.coffee:22:3, <js>:10:18)
  at Robot.loadExternalScripts (/home/dmichael/Repo/review_hubot/node_modules/hubot/src/robot.coffee:401:11, <js>:272:39)
  at /home/dmichael/Repo/review_hubot/node_modules/hubot/bin/hubot:152:11, <js>:159:26
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

**Comment by benpbolton** [comment]
@1davidmichael  🤔  ... is it possible that the package `coffee-script` is somehow missing?

In the same directory, can you attempt a `npm install coffee-script --save` and then a `bin/hubot` to test?

**Comment by 1davidmichael** [comment]
That worked! Thanks, should have been installed as a dependency so may be something wrong on my end.

**Comment by avaldivi** [comment]
@benpbolton I am having this same issue from above and ran `npm install coffee-script --save` but it is still an error I also did coffelint but that also was not a solution. Have an idea?

```
{
  "name": "gitqueue",
  "version": "0.0.0",
  "private": true,
  "author": "Adrianna Valdivia <adrianna.valdivia@salesloft.com>",
  "description": "Pull Request Organizer",
  "dependencies": {
    "coffee-script": "^1.12.7",
    "coffeelint": "^2.1.0",
    "hubot": "^3.3.2",
    "hubot-code-review": "^0.6.6",
    "hubot-diagnostics": "^1.0.0",
    "hubot-google-images": "^0.2.7",
    "hubot-google-translate": "^0.2.1",
    "hubot-help": "^1.0.1",
    "hubot-heroku-keepalive": "^1.0.3",
    "hubot-maps": "0.0.3",
    "hubot-pugme": "^0.1.1",
    "hubot-redis-brain": "^1.0.0",
    "hubot-rules": "^1.0.0",
    "hubot-scripts": "^2.17.2",
    "hubot-shipit": "^0.2.1",
    "hubot-slack": "^4.6.0"
  },
  "engines": {
    "node": "10.13.0"
  }
}
```

```
[Thu Apr 18 2019 19:52:07 GMT-0400 (Eastern Daylight Time)] INFO hubot-redis-brain: Using default redis on localhost:6379
[Thu Apr 18 2019 19:52:07 GMT-0400 (Eastern Daylight Time)] ERROR Unable to load /Users/adriannavaldivia/src/my-awesome-hubot/node_modules/hubot-code-review/src/code-reviews: SyntaxError: unexpected MATH
  at Object.exports.throwSyntaxError (/Users/adriannavaldivia/src/my-awesome-hubot/node_modules/coffeescript/lib/coffee-script/helpers.js:197:13)
  at Parser.parser.yy.parseError (/Users/adriannavaldivia/src/my-awesome-hubot/node_modules/coffeescript/lib/coffee-script/coffee-script.js:265:20)
  at Parser.parse (/Users/adriannavaldivia/src/my-awesome-hubot/node_modules/coffeescript/lib/coffee-script/parser.js:537:22)
  at compile (/Users/adriannavaldivia/src/my-awesome-hubot/node_modules/coffeescript/lib/coffee-script/coffee-script.js:35:24)
  at Object.loadFile (/Users/adriannavaldivia/src/my-awesome-hubot/node_modules/coffeescript/lib/coffee-script/coffee-script.js:176:14)
  at Module.load (/Users/adriannavaldivia/src/my-awesome-hubot/node_modules/coffeescript/lib/coffee-script/coffee-script.js:211:36)
  at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
  at Function.Module._load (internal/modules/cjs/loader.js:529:3)
  at Module.require (internal/modules/cjs/loader.js:636:17)
  at require (internal/modules/cjs/helpers.js:20:18)
  at Object.<anonymous> (/Users/adriannavaldivia/src/my-awesome-hubot/node_modules/hubot-code-review/src/code-reviews.coffee:10:15, <js>:4:17)
  at Object.<anonymous> (/Users/adriannavaldivia/src/my-awesome-hubot/node_modules/hubot-code-review/src/code-reviews.coffee:10:1, <js>:350:4)
  at Module._compile (internal/modules/cjs/loader.js:688:30)
  at Object.loadFile (/Users/adriannavaldivia/src/my-awesome-hubot/node_modules/coffeescript/lib/coffee-script/coffee-script.js:182:19)
  at Module.load (/Users/adriannavaldivia/src/my-awesome-hubot/node_modules/coffeescript/lib/coffee-script/coffee-script.js:211:36)
  at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
  at Function.Module._load (internal/modules/cjs/loader.js:529:3)
  at Module.require (internal/modules/cjs/loader.js:636:17)
  at require (internal/modules/cjs/helpers.js:20:18)
  at Robot.loadFile (/Users/adriannavaldivia/src/my-awesome-hubot/node_modules/hubot/src/robot.js:360:22)
  at module.exports (/Users/adriannavaldivia/src/my-awesome-hubot/node_modules/hubot-code-review/index.coffee:22:3, <js>:10:18)
  at packages.forEach.pkg (/Users/adriannavaldivia/src/my-awesome-hubot/node_modules/hubot/src/robot.js:409:52)
  at Array.forEach (<anonymous>:null:null)
  at Robot.loadExternalScripts (/Users/adriannavaldivia/src/my-awesome-hubot/node_modules/hubot/src/robot.js:409:25)
  at /Users/adriannavaldivia/src/my-awesome-hubot/node_modules/hubot/bin/hubot.js:207:13
  at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```
