### ISSUE TITLE
channel_not_found if used in direct chat

### ISSUE THREAD

**Issue by estahn** [alleyinteractive/hubot-code-review#9]
```error: Response not OK:  channel_not_found
Unhandled rejection Error: channel_not_found
  at handleHttpResponse (/var/www/html/node_modules/@slack/client/lib/clients/transports/call-transport.js:103:17)
  at handleTransportResponse (/var/www/html/node_modules/@slack/client/lib/clients/transports/call-transport.js:153:19)
  at apply (/var/www/html/node_modules/lodash/lodash.js:499:17)
  at wrapper (/var/www/html/node_modules/lodash/lodash.js:5356:16)
  at Request.handleRequestTranportRes (/var/www/html/node_modules/@slack/client/lib/clients/transports/request.js:20:5)
  at apply (/var/www/html/node_modules/lodash/lodash.js:499:17)
  at Request.wrapper [as _callback] (/var/www/html/node_modules/lodash/lodash.js:5356:16)
  at Request.self.callback (/var/www/html/node_modules/request/request.js:188:22)
  at emitTwo (events.js:106:13)
  at Request.emit (events.js:194:7)
  at Request.<anonymous> (/var/www/html/node_modules/request/request.js:1171:10)
  at emitOne (events.js:96:13)
  at Request.emit (events.js:191:7)
  at IncomingMessage.<anonymous> (/var/www/html/node_modules/request/request.js:1091:12)
  at Object.onceWrapper (events.js:293:19)
  at emitNone (events.js:91:20)
  at IncomingMessage.emit (events.js:188:7)
  at endReadableNT (_stream_readable.js:975:12)
  at _combinedTickCallback (internal/process/next_tick.js:80:11)
  at process._tickDomainCallback (internal/process/next_tick.js:128:9)```

**Comment by benpbolton** [comment]
thanks! What's the context for this workflow @estahn ? Dropping PRs directly to hubot?

**Comment by estahn** [comment]
Yes, that's correct. We have different focus teams which not necessarily need to be aware of all PRs. I would suspect it could reduce noise.

**Comment by benpbolton** [comment]
hmm, @estahn , hubot-code-review is intended to keep per-room lists, meaning that the focus teams could have a room/channel (or just a 2 user channel with themselves and the bot). 

In this manner, a `hubot list crs` in one room will be different than a `hubot list crs` in another. Due to the reliance on assuming room/channel interactions, this would be a challenging shift. Is it feasible for your workflow to maintain separate channels for focus groups that the bot may participate in?

**Comment by estahn** [comment]
@benpbolton Yes, that should be fine. We have hubot now in different rooms.
